[package]
name = "garlemlia-project"
version = "0.1.0"
edition = "2021"

[dependencies]
garlemlia = { path = "garlemlia" }
garlemlia-simulator = { path = "garlemlia-simulator" }
tokio = { version = "1.43.0", features = ["full"] }