[package]
name = "masters"
version = "0.1.0"
edition = "2021"

[dependencies]
kademlia = { path = "kademlia" }
kademlia-simulator = { path = "kademlia-simulator" }
rand = "0.9.0"
tokio = { version = "1.43.0", features = ["full"] }