[package]
name = "kademlia-simulator"
version = "0.1.0"
edition = "2021"

[dependencies]
kademlia = { path = "../kademlia" }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
tokio = "1.43.0"
rand = "0.9.0"