[package]
name = "kademlia"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1.43.0", features = ["rt", "rt-multi-thread"] }
serde_json = "1.0.138"
rand = "0.9.0"